src/MvcTesting/Controllers/GenreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcTesting.Models;
using MvcTesting.ViewModels;
using System.Collections.Generic;
using System.Linq;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MvcTesting.Controllers
{
    [Authorize(Roles="Admin")]
    public class GenreController : Controller
    { 

         private MovieCollectorContext _context;


    public GenreController(MovieCollectorContext dbContext)
        {
            _context = dbContext;
        }
    // GET: /<controller>/
    public IActionResult Index()
        {
            List<Genre> genres = _context.Genres.ToList();
            var vm = new GenreIndexViewModel() { Items = genres };
            return View(vm);
        }

        public IActionResult Add()
        {
            AddGenreViewModel addGenreViewModel = new AddGenreViewModel();
            return View(addGenreViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddGenreViewModel addGenreViewModel)
        {
            if (ModelState.IsValid)
            {
                Genre newGenre = new Genre { Name = addGenreViewModel.Name };
                _context.Genres.Add(newGenre);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(addGenreViewModel);
        }

        public IActionResult RemoveGenre()
        {
            List<Genre> genres = _context.Genres.ToList();
            RemoveGenreViewModel vm = new RemoveGenreViewModel() { Items = genres };
            return View(vm);
        }

        [HttpPost]
        public IActionResult RemoveGenre(int[] IDs)
        {
            foreach (int id in IDs)
            {
                Genre removeGenre = _context.Genres.SingleOrDefault(g => g.ID == id);
                _context.Genres.Remove(removeGenre);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Genre editGenre = _context.Genres.SingleOrDefault(g => g.ID == id);
            if (editGenre != null)
            {
                EditGenreViewModel vm = new EditGenreViewModel() { ID = id, Name = editGenre.Name };
                return View(vm);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(EditGenreViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Genre editGenre = _context.Genres.SingleOrDefault(g => g.ID == vm.ID);
                editGenre.Name = vm.Name;
                _context.SaveChanges();

            }


            return RedirectToAction("Index");
        }
    }
}

src/MvcTesting/Controllers/MediaController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MvcTesting.Models;
using MvcTesting.ViewModels;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MvcTesting.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MediaController : Controller
    {
        private MovieCollectorContext _context;


        public MediaController(MovieCollectorContext dbContext)
        {
            _context = dbContext;
        }

        public IActionResult Index()
        {
            List<MediaFormat> mediaFormats = _context.MediaFormats.ToList();
            var vm = new MediaIndexViewModel() { Items = mediaFormats };

            return View(vm);
        }

        public IActionResult Add()
        {
            AddMediaFormatViewModel addMediaFormatViewModel = new AddMediaFormatViewModel();

            return View(addMediaFormatViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddMediaFormatViewModel addMediaFormatViewModel)
        {
            if (ModelState.IsValid)
            {
                MediaFormat newMediaFormat = new MediaFormat { Name = addMediaFormatViewModel.Name };
                _context.MediaFormats.Add(newMediaFormat);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(addMediaFormatViewModel);
        }

        public IActionResult Remove()
        {
            List<MediaFormat> mediaFormats = _context.MediaFormats.ToList();
            RemoveMediaFormatViewModel vm = new RemoveMediaFormatViewModel() { Items = mediaFormats };
            return View(vm);
        }

        [HttpPost]
        public IActionResult Remove(int[] IDs)
        {
            foreach (int id in IDs)
            {
                MediaFormat removeMediaFormat = _context.MediaFormats.SingleOrDefault(m => m.ID == id);
                _context.MediaFormats.Remove(removeMediaFormat);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            MediaFormat editMediaFormat = _context.MediaFormats.SingleOrDefault(g => g.ID == id);
            if (editMediaFormat != null)
            {
                EditMediaFormatViewModel vm = new EditMediaFormatViewModel() { ID = id, Name = editMediaFormat.Name };
                return View(vm);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(EditMediaFormatViewModel vm)
        {
            if (ModelState.IsValid)
            {
                MediaFormat editMediaFormat = _context.MediaFormats.SingleOrDefault(m => m.ID == vm.ID);
                editMediaFormat.Name = vm.Name;
                _context.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }
    }
}

src/MvcTesting/Views/Shared/_EditItemPartial.cshtml
<form asp-controller="@Model.Controller" asp-action="@Model.Action" method="post">
    <div class="form-group">
        <label for="Name">@Model.Controller Name:</label>
        <input type="text" class="form-control" name="Name" value="@Model.Name"/>
        <input type="hidden" name="ID" value="@Model.ID" />
        <br />
        <button class="btn btn-primary" type="submit">Save Changes</button>
    </div>
</form>

src/MvcTesting/Views/Shared/_FilmOptionsPartial.cshtml
@model Film

@if (Model.UserID == UserManager.GetUserId(User) || User.IsInRole("Admin"))
{
    
    <a class="btn btn-primary" asp-controller="Movie" asp-action="Edit" asp-route-id="@Model.ID">Edit this Movie</a>
}
@if (User.Identity.IsAuthenticated && Model.UserID != UserManager.GetUserId(User))
{
    <a class="btn btn-primary" asp-controller="Movie" asp-action="Copy" asp-route-id="@Model.ID">Copy this Movie</a>
}

src/MvcTesting/Views/Shared/_ItemIndexPartial.cshtml
<table class="table">
    <tr>
        <th>Name</th>
        <th>Action</th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model.Items)
    {
        <tr>
            <td>@item.Name</td>
            <td><a asp-controller="@Model.Controller" asp-action="Edit" asp-route-id="@item.ID">Edit</a></td>
            <td></td>
            <td></td>
        </tr>
        
    }
</table> 

src/MvcTesting/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieLot</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-slate.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Movie" asp-action="Index" class="navbar-brand">MovieLot</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Movies<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li style="width: 275px">
                                <form class="navbar-form navbar-left" asp-controller="Movie" asp-action="Search" method="post">
                                    <div class="input-group">
                                        <label for="UserQuery"></label>
                                        <input type="text" class="form-control" name="SearchValue" placeholder="Search User Movies" />
                                        <div class="input-group-btn">
                                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                        </div>
                                    </div>

                                </form>
                            </li>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li style="width: 275px">
                                    <form class="navbar-form navbar-left" asp-controller="Movie" asp-action="WebSearch" method="post">
                                        <div class="input-group">
                                            <label for="query"></label>
                                            <input type="text" class="form-control" name="query" placeholder="Search the Web"/>
                                            <input type="hidden" name="page" value="1" />
                                            <div class="input-group-btn">
                                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                            </div>
                                        </div>
                                    </form>
                                </li>
                                <li><a asp-area="" asp-controller="Movie" asp-action="Index">Index</a></li>
                                <li><a asp-area="" asp-controller="Movie" asp-action="Add">Add</a></li>
                                //<li><a asp-area="" asp-controller="Movie" asp-action="Remove">Remove</a></li>
                                <li>@Html.ActionLink("Remove", "Remove", "Movie")</li>
                            }
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Users<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li style="width: 275px">
                                <form class="navbar-form navbar-left" asp-controller="Users" asp-action="Search" method="post">
                                    <div class="input-group">
                                        <label for="UserQuery"></label>
                                        <input type="text" class="form-control" name="UserQuery" placeholder="Search for User" />
                                        <div class="input-group-btn">
                                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                        </div>
                                    </div>
                                    
                                </form>
                            </li>
                            <li><a asp-area="" asp-controller="Users" asp-action="Index">Index</a></li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li><a asp-area="" asp-controller="Users" asp-action="ViewRoles">Roles</a></li>
                                @*<li><a asp-area="" asp-controller="Users" asp-action="DeleteUser">Delete</a></li>*@
                            }
                         </ul>
                     </li>
                     @if (User.IsInRole("Admin"))
                     {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Genres<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Genre" asp-action="Index">Index</a></li>
                                <li><a asp-area="" asp-controller="Genre" asp-action="Add">Add</a></li>
                                <li><a asp-area="" asp-controller="Genre" asp-action="RemoveGenre">Delete</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Media<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Media" asp-action="Index">Index</a></li>
                                <li><a asp-area="" asp-controller="Media" asp-action="Add">Add</a></li>
                                <li><a asp-area="" asp-controller="Media" asp-action="Remove">Delete</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Audio<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="AudioFormat" asp-action="Index">Index</a></li>
                                <li><a asp-area="" asp-controller="AudioFormat" asp-action="Add">Add</a></li>
                                <li><a asp-area="" asp-controller="AudioFormat" asp-action="Remove">Delete</a></li>
                            </ul>
                        </li>

                     }

                     <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                     <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                        @await Html.PartialAsync("_LoginPartial")
</div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <img id="TMDB" src="~/images/tmdb.png" /> <span id="copyright">&copy; 2019 - MovieLot</span> 
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/MvcTesting/Views/Shared/_MainFilmInfoPartial.cshtml
@model ViewMovieViewModel

<div class="col-md-10 main-film-top-margin">
    <div class="row">
        <div class="col-md-4 poster">
            <div class="center-block">
                <img src="@Model.PosterUrl" class="img-responsive" />
            </div>
        </div>
        <div class="col-md-8">
            <div class="row main-film-info margin-right-offset" style="border-bottom:3px groove gray">
                <h1>
                    <span style="color: ghostwhite;">@Model.Film.Name</span><small> @Model.DisplayYear</small>
                    @if (Model.Film.ID > 0)
                    {
                        @if (Model.Film.UserID == UserManager.GetUserId(User) || User.IsInRole("Admin"))
                        {

                            <a class="btn btn-primary" asp-controller="Movie" asp-action="Edit" asp-route-id="@Model.Film.ID">Edit this Movie</a>
                        }
                        @if (User.Identity.IsAuthenticated && Model.Film.UserID != UserManager.GetUserId(User))
                        {
                            <a class="btn btn-primary" asp-controller="Movie" asp-action="Copy" asp-route-id="@Model.Film.ID">Copy this Movie</a>
                        }
                        //Html.Partial("_FilmOptionsPartial", Model.Film); - Not sure why this wasn't working - Not needed anyway.
                    }
                </h1>
            </div>

            @if (!string.IsNullOrEmpty(Model.Film.Overview))
            {
                <div class="row main-film-info">
                    <h2>Synopsis</h2>
                    @Model.Film.Overview
                    <br />
                </div>
            }
            @if (Model.CastMembers.Count > 0)
            {
                <div class="row main-film-info">
                    <h2>Top Cast Members</h2>
                </div>
                <div class="row">
                    @foreach (var castMember in Model.CastMembers)
                    {
                        <div class="col-md-4 cast-display">
                            @castMember
                        </div>
                    }
                </div>
            }
            @if (!string.IsNullOrEmpty(Model.Comments))
            {
                <div class="row main-film-info">
                    <h2>Comments from @Model.FilmOwnerName</h2>
                    <p>@Model.Comments</p>
                </div>
            }
        </div>
    </div>
    <br />
    @if (!string.IsNullOrEmpty(Model.Film.TrailerUrl))
    {
        <div class="row embed-responsive embed-responsive-16by9 margin-right-offset">
            <iframe class="embed-responsive-item" src="@Model.Film.TrailerUrl" frameborder="0" allowfullscreen></iframe>
        </div>
    }
</div>

src/MvcTesting/Views/Shared/_MovieDataEntryPartial.cshtml
@model AddMovieViewModel

<label class="control-label" asp-for="Name"></label>
<input class="form-control" type="text" asp-for="Name" />
<span asp-validation-for="Name"></span>

<label class="control-label" asp-for="Year"></label>
<input class="form-control" type="text" asp-for="Year" />
<span asp-validation-for="Year"></span>

<label class="control-label" asp-for="Runtime"></label>
<input class="form-control" type="text" asp-for="Runtime" />
<span asp-validation-for="Runtime"></span>

<label class="control-label" asp-for="MediaID"></label>
<select class="form-control" asp-for="MediaID" asp-items="Model.MediaFormats"></select>
<span asp-validation-for="MediaID"></span>

<label class="control-label" asp-for="AudioID"></label>
<select class="form-control" asp-for="AudioID" asp-items="Model.AudioFormats"></select>
<span asp-validation-for="AudioID"></span>

<label class="control-label" asp-for="AspectRatio"></label>
<input class="form-control" type="text" asp-for="AspectRatio" />
<span asp-validation-for="AspectRatio"></span>

<label class="control-label" asp-for="Comments"></label>
<textarea class="form-control" asp-for="Comments"></textarea>
<span asp-validation-for="Comments"></span>

<label class="control-label" asp-for="Rating"></label>
<select class="form-control" asp-for="Rating" asp-items="Model.Ratings"></select>
<span asp-validation-for="Rating"></span>

<label class="control-label" asp-for="Overview"></label>
<input class="form-control" type="text" asp-for="Overview" />
<span asp-validation-for="Overview"></span>

<label class="control-label" asp-for="TrailerUrl"></label>
<input class="form-control" type="text" asp-for="TrailerUrl" />
<span asp-validation-for="TrailerUrl"></span>

<label class="control-label" asp-for="PosterUrl"></label>
<input class="form-control" type="text" asp-for="PosterUrl" />
<span asp-validation-for="PosterUrl"></span>

<label class="control-label" asp-for="Has3D"></label>
<input type="checkbox" asp-for="Has3D" />
<br />

<label class="control-label" asp-for="Directors"></label>
<textarea class="form-control" rows="5" asp-for="Directors"></textarea>
<span asp-validation-for="Directors"></span>
<br />

<label class="control-label" asp-for="Cast"></label>
<textarea class="form-control" rows="5" asp-for="Cast"></textarea>
<span asp-validation-for="Cast"></span>
<br />

<div class="panel panel-default">
    <div class="panel-heading"><label asp-for="Genres"></label></div>
    <div class="panel-body">
        @foreach (var genre in Model.AvailableGenres)
        {
            <label class="checkbox-inline"><input type="checkbox" name="Genres" value="@genre.Value" checked="@genre.Selected"/>@genre.Text</label>
        }
    </div>
</div>
<p><input type="checkbox" asp-for="IsPrivate" /><label asp-for="IsPrivate"></label></p>

src/MvcTesting/Views/Shared/_RemoveItemPartial.cshtml
<form asp-controller="@Model.Controller" asp-action="@Model.Action" method="post">
    @foreach (var item in Model.Items)
    {
        <label for="@item.Name">@item.Name</label>
        <input type="checkbox" name="IDs" value="@item.ID" />
        <br />

    }

    <button class="btn btn-danger" type="submit">Delete Items</button>

</form>

src/MvcTesting/Views/Shared/_SecondaryFilmInfoPartial.cshtml
@model ViewMovieViewModel

<div class="col-md-2 extra-film-info">
    @* Film User Image, Name, Collection Count, Film Media Format, Film Audio FOrmat, Runtime, 3D?, Genre, and user rating goes here. *@
    @if (!string.IsNullOrEmpty(Model.Film.UserID))
    {
        <div class="row">
            <img src="@Model.OwnerProfilePicture" class="image-centered profilePicture" />
        </div>
        <div class="row text-centered">
            <a asp-controller="Users" asp-action="DisplayUser" asp-route-username="@Model.FilmOwnerName">@Model.FilmOwnerName (@Model.OwnerCollectionSize)</a>
        </div>
        <hr />
    }

    <div class="film-stats">
        <div class="row">
            <h4>Directed By:</h4>
            <p>@Model.Directors</p>
        </div>
        <div class="row">
            <h4>Runtime <small>(in minutes)</small>:</h4>
            <p>@Model.RunTime</p>
        </div>
        
        @if (Model.Genres.Count > 0)
            {
            <div class="row">
                <h4>Genres</h4>
                <ul>
                    @foreach (var genre in Model.Genres)
                    {
                        <li>
                            <form asp-controller="Movie" asp-action="Search" method="post">
                                <button class="filter-link" type="submit" name="GenreFilter" value="@genre.Genre.Name">@genre.Genre.Name</button>
                            </form>
                        </li>
                    }
                </ul>
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.Film.UserID))
        {
            <div class="row">
                <form asp-controller="Movie" asp-action="Search" method="post">
                    <h4>Format:</h4>
                    <button class="filter-link" type="submit" name="MediaFilter" value="@Model.MediaFormat">@Model.MediaFormat</button>
                </form>
            </div>
            <div class="row">
                <form asp-controller="Movie" asp-action="Search" method="post">
                    <h4>Audio:</h4>
                    <button class="filter-link" type="submit" name="AudioFilter" value="@Model.AudioFormat">@Model.AudioFormat</button>
                </form>
            </div>
            <div class="row">
                <h4>Playable in 3D?</h4>
                <p>@Model.OptionFor3D</p>
            </div>
        }
    </div>
</div>

src/MvcTesting/Views/Shared/_ValidationSummary.cshtml
<form class="form-horizontal" asp-antiforgery="true">
    <fieldset>
        @if (!@ViewData.ModelState.IsValid)
        {
            var errors = ViewData.ModelState.Values.Select(item => item.Errors.FirstOrDefault()?.ErrorMessage).Where(item => item != null);
            <div class="alert alert-danger">
                <span>There are problems with your input:</span>
                <ul>
                    @foreach (var error in errors)
                    {
                        <li>@error</li>
                    }
                </ul>
            </div>
        }
    </fieldset>
</form>